Vagrant.configure("2") do |config|
  config.vm.define "chocolatey" do |db|
    db.vm.box = "StefanScherer/windows_2016"
    db.vm.hostname = "chocolatey"
    db.winrm.basic_auth_only = true
    db.vm.communicator = "winrm"

    db.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
    db.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true
    db.vm.network :forwarded_port, guest: 22, host: 2222, id: "ssh", auto_correct: true

    db.vm.synced_folder "../packages", "/packages"
    db.vm.synced_folder "../.", "/vagrant"

    db.vm.provider :virtualbox do |v, override|
      override.vm.network :private_network, ip: "192.168.38.2"
      # linked clones for speed and size
      v.linked_clone = true if Vagrant::VERSION >= '1.8.0'
      v.gui = true
      v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      v.customize ["modifyvm", :id, "--memory", "3072"]
      v.customize ["modifyvm", :id, "--audio", "none"]
      v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
      v.customize ["modifyvm", :id, "--draganddrop", "hosttoguest"]
      v.customize ["modifyvm", :id, "--usb", "off"]
      v.customize ["setextradata", "global", "GUI/SuppressMessages", "all"]
    end

    # privileged:false - https://github.com/hashicorp/vagrant/issues/9138
    # Auto Login issue corrected, as per discussion here: https://twitter.com/stefscherer/status/1011120268222304256
    db.vm.provision "shell", privileged: false, inline: <<-SHELL
      Set-ItemProperty "HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon" -Name AutoAdminLogon -Value 1
      Set-ItemProperty "HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon" -Name DefaultUserName -Value "vagrant"
      Set-ItemProperty "HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon" -Name DefaultPassword -Value "vagrant"
      Remove-ItemProperty "HKLM:\\SOFTWARE\\Microsoft\\Windows NT\\CurrentVersion\\Winlogon" -Name AutoAdminLogonCount -Confirm -ErrorAction SilentlyContinue
    SHELL
    db.vm.provision "reload"
    db.vm.provision :shell, :path => "../shell/PrepareWindows.ps1", privileged: false
    db.vm.provision :shell, :path => "../shell/SetWindowsPreferences.ps1", privileged: false
    db.vm.provision :shell, :path => "../shell/InstallChocolatey.ps1", privileged: false
    db.vm.provision :shell, path: "scripts/Provision.ps1", privileged: false
  end
end
